### ISSUE TITLE
Issue Resolving dependencies

### ISSUE THREAD

**Issue by rakshith-porter** [peiffer-innovations/json_theme#100]
Error:
```
Because json_theme >=6.0.0 depends on json_schema ^5.0.0 which depends on http ^0.13.4, json_theme >=6.0.0 requires http ^0.13.4.
So, because <MyApp> depends on both http ^1.0.0 and json_theme 6.0.0, version solving failed.
exit code 1
```
MyApp dependencies:
```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  video_player: ^2.6.1
  json_theme: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```
